config/routes.rb
Rails.application.routes.draw do
  get 'profile/index'

  get 'profile/update'

  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }
  get 'index/index'

  root 'index#index'

end

app/models/brake_type.rb
class BrakeType < ActiveRecord::Base
  has_many :front_brake_type , class_name: "Feature", foreign_key: "front_brake_type_id"
  has_many :rear_brake_type , class_name: "Feature", foreign_key: "rear_brake_type_id"
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :models
end

app/models/engine_cooling_system.rb
class EngineCoolingSystem < ActiveRecord::Base
  has_many :features
end

app/models/engine_cylinder_placement.rb
class EngineCylinderPlacement < ActiveRecord::Base
  has_many :features
end

app/models/engine_final_transmission.rb
class EngineFinalTransmission < ActiveRecord::Base
  has_many :features
end

app/models/engine_fuel_system.rb
class EngineFuelSystem < ActiveRecord::Base
  has_many :features
end

app/models/engine_type.rb
class EngineType < ActiveRecord::Base
  has_many :features
end

app/models/feature.rb
class Feature < ActiveRecord::Base
  has_one :model
  belongs_to :engine_final_transmission
  belongs_to :engine_type
  belongs_to :engine_fuel_system
  belongs_to :engine_cylinder_placement
  belongs_to :engine_cooling_system
  belongs_to :ignition_system
  belongs_to :starter_system
  belongs_to :front_brake_type, :class_name => 'BrakeType', :foreign_key => 'front_brake_type_id'
  belongs_to :rear_brake_type, :class_name => 'BrakeType', :foreign_key => 'rear_brake_type_id'
end

app/models/ignition_system.rb
class IgnitionSystem < ActiveRecord::Base
  has_many :features
end

app/models/model.rb
class Model < ActiveRecord::Base
  belongs_to :feature
  has_and_belongs_to_many :profiles
  belongs_to :brand
  belongs_to :type
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user, dependent: :destroy, autosave: true
  has_and_belongs_to_many :models
end

app/models/starter_system.rb
class StarterSystem < ActiveRecord::Base
  has_many :features
end

app/models/type.rb
class Type < ActiveRecord::Base
  has_many :models
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
      "profile/index"
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
      
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index
  end

  def update
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/index/create.html.erb
<h2>Страница создания</h2>
<ul>
  <% @tests.each do |test| %>
    <li><%= test %></li>
  <% end %>
  <%= link_to 'На главную', controller: 'index' %>
</ul>

app/views/index/index.html.erb
<%= render partial: 'partials/sign_in_form' %>
<%= render partial: 'partials/sign_up_form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Motosocial</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="header row" style="margin-top:10px">
    <ul class="nav nav-pills col-md-10 col-md-offset-1 clearfix">
      <li><a href="#">Главная</a></li>
      <li><a href="#">Профиль</a></li>
      <li><a href="#">Сообщения</a></li>
      <li class="pull-right"><a href="#" data-toggle="modal" data-target="#modal__signin">Войти</a></li>
    </ul>
  </div>
<%= yield %>

</body>
</html>

app/views/partials/_sign_in_form.html.erb
<div class="modal modal-signin fade" id="modal__signin">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="row">
        <div class="col-md-12">
          <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
              <h3>Авторизация</h3>
          </div>
          <%= form_for(:user, html: {class: "form-horizontal"}, :url => session_path(:user)) do |f| %>
          <div class="modal-body">
              <%= f.label "Email" %>
              <%= f.text_field :email %>
              <%= f.label "Пароль" %>
              <%= f.password_field :password %>
              <%= f.check_box :remember_me %>
              <%= f.label "Запомнить меня" %>
          </div>
          <div class="modal-footer">
              <%= f.submit 'Войти', class: "btn btn-success" %>
              <%= link_to "Забыли пароль?", new_password_path(:user) %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/partials/_sign_up_form.html.erb
<div class="modal modal-signup fade" id="modal__signup">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="row">
        <div class="col-md-12">
          <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
              <h3>Регистрация</h3>
          </div>
          <div class="modal-body">
          <%= form_for(User.new, as: :user, html: {class: "form-horizontal"}, url: registration_path(:user)) do |f| %>
            <%= devise_error_messages! %>

            <div class="field form-group">
              <%= f.label :email, class: "col-sm-3 control-label" %>
              <div class="col-md-9">
                <%= f.email_field :email, autofocus: true,  class: "form-control" %>
              </div>
            </div>
            <%= fields_for Profile.new do |p| %>
              <div class="field form-group">
                <%= p.label "Имя", class: "col-sm-3 control-label" %>
                <div class="col-md-9">
                  <%= p.text_field :firstname, autofocus: true, class: "form-control" %>
                </div>
              </div>

              <div class="field form-group">
                <%= p.label "Фамилия", class: "col-sm-3 control-label" %>
                <div class="col-md-9">
                  <%= p.text_field :surname, autofocus: true, class: "form-control" %>
                </div>
              </div>
            <% end %>

            <div class="field form-group">
              <%= f.label "Пароль", class: "col-sm-3 control-label" %>
              <% if @minimum_password_length %>
              <em>(<%= @minimum_password_length %> characters minimum)</em>
              <% end %>
              <div class="col-md-9">
                <%= f.password_field :password, autocomplete: "off", class: "form-control" %>
              </div>
            </div>

            <div class="field form-group">
              <%= f.label "Подтвердите пароль", class: "col-sm-3 control-label" %>
              <div class="col-md-9">
                <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control" %>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <div class="actions">
              <%= f.submit "Зарегистрироваться",  class: "btn btn-success pull-right" %>
            </div>
            <% end %>
            <div style="clear:both"><div>
              <br />
            <%= render "devise/shared/links" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>